version: "3.9"

services:  
  api:
    image: netiim/api-tech-challenge:1.0
    container_name: api-tech-challenge
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - tech-bridge
    ports:
      - "5001:8080"
      - "5002:8081"
  db:
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    networks:
      - tech-bridge
    environment:
      SA_PASSWORD: "YourStrongPassword1!"
      ACCEPT_EULA: "Y"

networks:
  tech-bridge:
    driver: bridge
    
