version: "3.9"

services:  
  # Serviço da Aplicação .NET
  api-contato:
    image: netiim/api-tech-challenge:latest
    container_name: api-tech-challenge
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=TechChallenge;User ID=sa;Password=YourStrongPassword1!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - tech-bridge
    ports:
      - "5001:8080"
      - "5002:8081"
      
  api-contato-post:
    image: netiim/contato-post:latest
    container_name: contato-post
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=TechChallenge;User ID=sa;Password=YourStrongPassword1!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - tech-bridge
    ports:
      - "5005:8080"
      - "5006:8081"
      
  api-contato-delete:
    image: netiim/contato-delete:latest
    container_name: contato-delete
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=TechChallenge;User ID=sa;Password=YourStrongPassword1!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - tech-bridge
    ports:
      - "5007:8080"
      - "5008:8081"   
      
  api-contato-put:
    image: netiim/contato-put:latest
    container_name: contato-put
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=TechChallenge;User ID=sa;Password=YourStrongPassword1!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - tech-bridge
    ports:
      - "5009:8080"
      - "5010:8081"
      
  api-contato-get:
    image: netiim/contato-get:latest
    container_name: contato-get
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=TechChallenge;User ID=sa;Password=YourStrongPassword1!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - tech-bridge
    ports:
      - "5011:8080"
      - "5012:8081"


  # Serviço do Banco de Dados
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql-server
    ports:
      - "1433:1433"
    networks:
      - tech-bridge
    environment:
      SA_PASSWORD: "YourStrongPassword1!"
      ACCEPT_EULA: "Y"

networks:
  tech-bridge:
    driver: bridge
