{
 "title": "API-TechChallenge",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Intervalo",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "Instâncias",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Duração das solicitações HTTPs",
   "type": "timeseries",
   "description": "refere-se ao tempo que uma solicitação HTTP leva desde o momento em que é recebida pelo servidor até que a resposta é enviada de volta ao cliente. ",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Solicitações em andamento",
   "type": "timeseries",
   "description": "refere-se ao número de solicitações que estão atualmente sendo processadas por um servidor ou aplicação.",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Início do processo",
   "type": "stat",
   "description": "refere-se ao momento em que um processo é iniciado no sistema operacional. ",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance =~ \"$instances\"} * 1000"
    }
   ]
  },
  {
   "title": " Contagem de coleta do GC",
   "type": "timeseries",
   "description": "refere-se ao número de vezes que o coletor de lixo (Garbage Collector, GC) foi executado para liberar memória não utilizada em um ambiente de execução de software, como uma aplicação .NET. ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Total de memória alocada",
   "type": "timeseries",
   "description": "refere-se à quantidade total de memória que foi alocada por um processo ou aplicação durante sua execução. Esse valor pode incluir tanto a memória atualmente em uso quanto a memória que foi alocada mas ainda não foi liberada.",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Número total de threads",
   "type": "timeseries",
   "description": "refere-se ao total de threads que um processo ou aplicação está utilizando em determinado momento. ",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Número de handles abertos",
   "type": "timeseries",
   "description": "refere-se ao número de identificadores abertos em um sistema operacional. Um \"handle\" é um ponteiro ou referência para um recurso de sistema, como um arquivo, uma conexão de rede, uma sessão de usuário, entre outros.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Conjunto de trabalho do processo",
   "type": "timeseries",
   "description": "refere-se ao conjunto de páginas de memória que um processo está atualmente usando e que estão na memória física (RAM). Esse conjunto de páginas inclui aquelas que foram recentemente referenciadas pelo processo e que estão prontamente disponíveis para uso imediato, sem necessidade de serem carregadas do disco.",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}