{
 "title": "RabbitMQ Dashboard (Prometheus Exporter)",
 "description": "Tested with latest prometheus exporter, 2019-09",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(rabbitmq_channelsTotal, service)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(rabbitmq_channelsTotal, pod)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(rabbitmq_channelsTotal, namespace)"
   },
   {
    "name": "queue",
    "label": "queue",
    "query": "label_values(rabbitmq_queue_messages_get_total, queue)"
   },
   {
    "name": "vhost",
    "label": "vhost",
    "query": "label_values(rabbitmq_queue_messages_get_total, vhost)"
   }
  ]
 },
 "panels": [
  {
   "title": "$pod Messages",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_messages_ready{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "$pod Consumers",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_consumers{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_consumers{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Consumers"
    }
   ]
  },
  {
   "title": "$pod Connections",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_connections{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Connections"
    }
   ]
  },
  {
   "title": "$pod Channels",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_channels{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Channels"
    }
   ]
  },
  {
   "title": "$pod Queues",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (queue) (rabbitmq_queues{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queues{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Queues"
    }
   ]
  },
  {
   "title": "MSGS PUB by $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_published_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_messages_published_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "MSGS SUBS by $pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_consumers{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_consumers{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_process_resident_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_process_resident_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Disk Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_disk_writes_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_disk_writes_total{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Queue Size (Bytes)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"}) / count(rabbitmq_queue_messages_bytes{namespace=~\"$namespace\", pod=~\"$pod\", service=~\"$service\"})",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Nodes UP",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod) (rabbitmq_queue_messages_ready))",
     "legendFormat": "$pod Messages"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (increase(rabbitmq_connections[1m])) / ignoring (pod) group_left count(rabbitmq_connections)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue, vhost, pod) (increase(rabbitmq_queue_messages[1m])) / ignoring (queue, vhost, pod) group_left count(rabbitmq_queue_messages)",
     "legendFormat": "[{{pod}}]-[{{queue}}]"
    }
   ]
  },
  {
   "title": "Messages Overview",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_ready{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_ready{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[READY] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_published_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_published_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[PUBLISHED] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[DELIVERED] {{queue}}"
    },
    {
     "expr": "sum by (queue) (increase(rabbitmq_queue_messages_delivered_noack_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"}[1m])) / ignoring (queue) group_left count(rabbitmq_queue_messages_delivered_noack_total{service=~\"$service\", pod=~\"$pod\", namespace=~\"$namespace\", queue=~\"$queue\", vhost=~\"$vhost\"})",
     "legendFormat": "[NOACK] {{queue}}"
    }
   ]
  }
 ]
}