version: "3.9"

services:  
  # Serviço do Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tech-bridge
    ports:
      - "9090:9090"   

  # Serviço do Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      - tech-bridge
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-mq
    ports:
      - "5672:5672"  # Porta de comunicação
      - "15692:15692" # Expondo a porta do Prometheus
      - "15672:15672" # Porta do console de gerenciamento (opcional)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - tech-bridge
      
volumes:
  grafana-storage:

networks:
  tech-bridge:
    driver: bridge
