version: "3.9"

services:  
  # Serviço da Aplicação .NET
  api-contato:
    image: netiim/api-tech-challenge:latest
    container_name: api-tech-challenge
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=TechChallenge;User ID=sa;Password=YourStrongPassword1!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - tech-bridge
    ports:
      - "5001:8080"
      - "5002:8081"
      
# Serviço da Aplicação .NET
  api-autenticacao:
    image: netiim/autenticacao-service:latest
    container_name: autenticacao-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=Autenticacao;User ID=sa;Password=YourStrongPassword1!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - tech-bridge
    ports:
      - "5005:8080"
      - "5006:8081"

  # Serviço do Banco de Dados
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql-server
    ports:
      - "1433:1433"
    networks:
      - tech-bridge
    environment:
      SA_PASSWORD: "YourStrongPassword1!"
      ACCEPT_EULA: "Y"

networks:
  tech-bridge:
    driver: bridge
