# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run unit tests
      run: dotnet test --no-build --filter "Categoria=Unidade"

    - name: Run validação banco para teste integração
      env:
        SA_PASSWORD: "StrongPassword!123"
        ACCEPT_EULA: "Y"
      run: dotnet test --no-build --filter "Categoria=VerificacaoDatabaseParaTesteIntegracao"
    
    - name: Run integration tests
      env:
        SA_PASSWORD: "StrongPassword!123"
        ACCEPT_EULA: "Y"
      run: dotnet test --no-build --filter "Categoria=integração" --logger trx
   
    - name: Get current version
      id: vars
      run: |
        echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        echo "NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true        
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/api-tech-challenge:${{ env.NEW_VERSION }}
          ${{ secrets.DOCKERHUB_USERNAME }}/api-tech-challenge:latest

    - name: Logout from Docker Hub
      run: docker logout
