name: CI

on:
  push:
    branches: [ "stage" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restaurando dependências
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Executando teste unitários
      run: dotnet test --no-build --filter "Categoria=Unidade"

    - name: Executando teste integração
      run: dotnet test --filter "Categoria=Integração" --verbosity detailed --logger "console;verbosity=detailed" --diag:log.txt
    
    - name: Pegar versão do git
      id: vars
      run: |
        echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
        echo "NEW_VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++;print}')" >> $GITHUB_ENV

    - name: Login no docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build e push da imagem
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true        
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/api-tech-challenge:${{ env.NEW_VERSION }}
          ${{ secrets.DOCKERHUB_USERNAME }}/api-tech-challenge:latest

    - name: Saindo do Docker Hub
      run: docker logout
