name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x' # Use the appropriate version for your project

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run unit tests
      run: dotnet test --no-build --filter "Category=Unit"

    - name: Run integration tests
      env:
        SA_PASSWORD: "yourStrong(!)Password"
        ACCEPT_EULA: "Y"
      run: dotnet test --no-build --filter "Category=Integration" --logger trx

    - name: Publish Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: '**/*.trx'
