name: .NET

on:
  push:
    branches: [ "git-action" ]
  pull_request:
    branches: [ "git-action" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: List all tests
      run: dotnet test --no-build --filter "Categoria=IntegraçãoGit" --list-tests
    - name: Test with dotnet
      run: dotnet test --filter "Categoria=Integração" --verbosity detailed --logger "console;verbosity=detailed" --diag:log.txt
