name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: List all tests
      run: dotnet test --no-build --filter "Categoria=integração" --list-tests
    - name: Run integration tests
      run: dotnet test --no-build --filter "Categoria=integração" --logger "console;verbosity=detailed" --blame-hang-timeout 5m
